version: '3.8'

services:
  odoo:
    image: odoo:17.0
    container_name: iload_odoo
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./odoo/addons:/mnt/extra-addons
      - odoo-data:/var/lib/odoo
    depends_on:
      - db
    restart: unless-stopped
    
  db:
    image: postgres:15
    container_name: iload_postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    
volumes:
  odoo-data:
  postgres-data: